repositories:
  - ./templates/react
  - ./templates/core
templates:
  customFc:
    source: ./templates/react/react-fc
    defaults:
      propsType: interface
      exportPropsType: false
      dummyProp: true
      filenameCase: snakeCase
      fileExtension: ts
